version: '3.5'

services:

#########################
### Minecraft servers ###
#########################

  # A hardcore world running on the vanilla server
  vanilla-hardcore:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./worlds/vanilla-hardcore:/data

  # An lobby world running on the Paper server
  paper-lobby:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
    volumes:
      - ./worlds/paper-lobby:/data

  paper-skyblock:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
    volumes:
      - ./worlds/paper-skyblock:/data      

#######################
### Minecraft proxy ###
#######################

  bungeecord:
    image: itzg/bungeecord
    environment:
      TYPE: "VELOCITY"
      
      # GeyserMC/Floodgate Plugins for Velocity
      PLUGINS: "https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/velocity/target/Geyser-Velocity.jar, https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/velocity/target/floodgate-velocity.jar"
    ports:
      - 25565:25577
      - 19132:19132/udp
    volumes:
      # Velocity config
      - ./config/velocity.toml:/server/velocity.toml

      # GeyserMC config
      - ./config/geyser.yml:/server/plugins/Geyser-Velocity/config.yml

      # Floodgate config
      - ./config/floodgate.yml:/server/plugins/floodgate/config.yml
      - ./secrets/key.pem:/server/plugins/floodgate/key.pem:ro
      - ./secrets/public-key.pem:/server/plugins/floodgate/public-key.pem:ro
      - ./secrets/encrypted.txt:/server/plugins/floodgate/encrypted.txt:ro
    links:
      - vanilla-hardcore